### ISSUE TITLE
Windows Cryptography Next Generation (CNG) is not supported on this platform.

### ISSUE THREAD

**Issue by balkarov** [thomasgalliker/PushNotifications.Server#29]
Hello. 

Thank you for your library, but it does not work for linux. 
I think you need replace ECDsaCng to ECDsa.Create()
Here you can see about it:
https://github.com/dotnet/core/issues/1918

**Comment by thomasgalliker** [comment]
Thanks @balkarov for reporting. I'm going to have a look at it.
How can I reproduce this issue? Which Linux distribution did you use? 
I was partially aware that there are problems with .NET and crypto on Linux, but I would rather prefer to not use another external dependency just to add Linux support. However, I'm positive we can get this issue solved.

**Comment by balkarov** [comment]
@thomasgalliker I tried on latest Mac OS, but I think it reproduced on any unix system.

**Comment by thomasgalliker** [comment]
Cool, I'm trying to reproduce it on my mac with VS Mac then.
Btw. do you know if I can - somehow - create a .p8 certificate file for testing purposes?

**Comment by balkarov** [comment]
For p8 certificate you should have apple developer account.

**Comment by thomasgalliker** [comment]
Yes, that's true. I just didn't want to commit my personal auth key file (.p8) to this public code repository. I need a .p8 file for unit testing purposes. Luckly I found a .p8 on the internet :)

**Comment by thomasgalliker** [comment]
I solved it but it requires .net standard 2.1. I'll soon publish a pre-release, hope this will work for you.

**Comment by thomasgalliker** [comment]
@balkarov I think I got this fixed. Can you please try the pre-release nuget [1.3.0-pre](https://www.nuget.org/packages/PushNotifications.Server/1.3.0-pre) and let me know if it works in your project. Kindly appreciated.

**Comment by balkarov** [comment]
@thomasgalliker I checked version 1.3.0-pre and it works on macOS Big Sure (11.4).
Thank you very much!

**Comment by thomasgalliker** [comment]
Cool. Thanks for reporting. I‘m going to merge it soon and you‘ll get a stable release.
